### ISSUE TITLE
GetPassWarning: Can not control echo on the terminal. Warning: Password input may be echoed.

### ISSUE THREAD

**Issue by ghost** [halfo/tag-tc#1] opened 2015-12-25 06:02 UTC
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py", line 137, in <module>
    if **name** == "**main**": main()
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py", line 124, in main
    login_attempt(driver)
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py", line 32, in login_attempt
    username_field = driver.find_element_by_name("handle")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 330, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 425, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061] No connection could be made because the target machine actively refused it

**Comment by halfo** [comment] 2015-12-25 08:33
Try running it on cmd.exe or windows PowerShell, instead of IDLE's. Also you can provide your username and password in script.py (line 6 and 7).

**Comment by ghost** [comment] 2015-12-25 09:43
I tried . It is showing this error

Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py",
line 137, in <module>
    if **name** == "**main**": main()
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py",
line 124, in main
    login_attempt(driver)
  File "C:\Users\Varun\Downloads\tag-tc-master\tag-tc-master\script\tag-tc.py",
line 32, in login_attempt
    username_field = driver.find_element_by_name("handle")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 330, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 712, in find_element
    {'using': by, 'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connectio
n.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connectio
n.py", line 426, in _request
    resp = self._conn.getresponse()
  File "C:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by halfo** [comment] 2015-12-25 11:02
It looks like topcoder has changed their links. I've updated my script accordingly. Please pull the latest commit and try again. I hope now it will work (as it is working on my machine xD).

**Comment by ghost** [comment] 2015-12-25 11:39
still it is showing the same error

**Comment by halfo** [comment] 2015-12-25 12:27
Well, I managed to reproduced it by closing the browser instance selenium is using. Did you by any chance do that?

**Comment by ghost** [comment] 2015-12-25 12:38
Where will the editorials be saved? I am getting editorials in browser

**Comment by halfo** [comment] 2015-12-25 12:44
Okay~~ Run the program, don't kill the browser instance, let it run. It takes around 40 minutes to do all the parsing and analysing. After that, the browser will automatically close. And there'll be an "index.html" file in the same directory where the script.py is located. I hope that helps.

**Comment by ghost** [comment] 2015-12-26 12:33
The index.html contains empty file of size 1KB. I have downloaded it twice even then it is empty.

**Comment by halfo** [comment] 2015-12-26 14:13
Did you provide it the list of keywords (the third point of "Usage" in documentation)?

**Closed as completed** 2015-12-26 15:59 UTC
